### ISSUE TITLE
Password file

### ISSUE THREAD

**Issue by sadov** [thunko/wall#1]
$ itmot
Ethereum Wallet Transfer
Please enter the account of SENDER:
0xdcA6ca7700c6e4E8514717F24257813505EEEc76
Please enter the account of RECEIVER:
0x0408B4D86a00f3d58eE17590D4891e25A3C44116
Please enter the AMOUNT of ethers:
0.1
Transaction code is:
Error: authentication needed: password or unlock at web3.js:3104:20 at web3.js:6191:15 at web3.js:5004:36 at <anonymous>:1:1

Seems you in your script using 'passwd' file, but in README not placed any information about it.

**Comment by thunko** [comment]
The script no longer uses the passwd file.

**Comment by sadov** [comment]
Please, don't close issues -- I will close them after checking of your fixes.

In current implementation passwd file still used:

$ sh -x ./itmot

    echo 'Ethereum Wallet Transfer'
    Ethereum Wallet Transfer
    pfile=./passwd
    ++ cat ./passwd
    cat: ./passwd: No such file or directory
....
