### ISSUE TITLE
Incorrect UI behavior

### ISSUE THREAD

**Issue by sadov** [thunko/wall#3]
Cancel button in dialog windows not handled -- application still run and at the last phase application without any data entered in inputbox widgets shows info-window "TRANSACTION number is:" with message "All updates are complete." Can this be fixed?

After entering of wrong data (SENDER, RECEIVER or AMOUNT) I see info-window "TRANSACTION number is:" with message "All updates are complete." again, but transaction was not happen. During the running of shell-script in debug mode I see error message from geth like this:

Ethereum Wallet Transfer Error: new BigNumber() not a number: qwe at raise (web3.js:14632:29) at web3.js:14620:33 at BigNumber (web3.js:13648:67) at BigNumber (web3.js:13658:29) at web3.js:2212:16 at web3.js:2190:23 at <anonymous>:1:131

Seems like "<" redirection sign in message -- the root of problem, without it message shows correctly. Is it possible to remove <> redirection symbols from error message before using in 'dialog' programm?

Running of itmo_ui after removing of passwd file finished by the same info-window with a message about unexistence of this file only in shell session, which generally invisible during the running of program from GUI. Can you fix it?

**Comment by thunko** [comment]
The bugs were corrected and the last question was not very clear to me. Nevertheless the passwd file is no longer needed for the script.

**Comment by sadov** [comment]
Please, don't close issues -- I will close them after checking of your fixes.

I mean -- if you using some files, you must show to user some information if such files is not exist, not silently finishing. In current implementation passwd file still used:

$ sh -x ./itmot
+ echo 'Ethereum Wallet Transfer'
Ethereum Wallet Transfer
+ pfile=./passwd
++ cat ./passwd
cat: ./passwd: No such file or directory
